name: pushTestArtefact

on:
  push:
    branches:
      - main

jobs:
  build_et_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm instal
        run: |
          npm install
      - name: npm run buld
        run: |
          npm run build --if-present
      - name: npm test
        run: |
          npm test
      - name: Artefact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md

  afficher_liste_fichiers:
    runs-on: ubuntu-latest
    needs: build_et_test
    steps:
      - name: Récupérer l'artefact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Afficher la liste des fichiers
        run: ls -l dist


