name: osef

jobs:
  mon-job:
  steps:
  - name: cache npm
  uses: actions/cache@v4
  with:
    path: ~/.npm
    key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install node modules
      run: npm ci
    - name: test
      run: npm run test
    - name: build
      run: npm run build
    - name: start
      run: npm run start
    - name: sommaire
      run: |
      echo "# Résumé du step" >> $GITHUB_STEP_SUMMARY
      echo "" >> $GITHUB_STEP_SUMMARY
